services:
  langgraph-api:
    environment:
      PGVECTOR_URI: "postgresql+psycopg2://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable"
  langgraph-postgres:
    image: pgvector/pgvector:pg16
  postgres-setup:
    image: migrate/migrate
    depends_on:
      langgraph-postgres:
        condition: service_healthy
    volumes:
      - ./backend/migrations:/migrations
    env_file:
      - .env
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable",
        "up",
      ]
  backend:
    container_name: opengpts-backend
    pull_policy: build
    build:
      context: backend
    ports:
      - "8100:8000" # Backend is accessible on localhost:8100
    depends_on:
      langgraph-api:
        condition: service_healthy
      postgres-setup:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - ./backend:/backend
    environment:
      POSTGRES_URI: "postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable"
      PGVECTOR_URI: "postgresql+psycopg2://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable"
      LANGGRAPH_URL: "http://langgraph-api:8000"
    command:
      - --reload
  frontend:
    container_name: opengpts-frontend
    pull_policy: build
    build:
      context: frontend
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend/src:/frontend/src
    ports:
      - "5173:5173" # Frontend is accessible on localhost:5173
    environment:
      VITE_BACKEND_URL: "http://backend:8000"
