version: '3'

services:
  redis:
    image: redislabs/redisearch:latest
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - opengpts

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-8100}:${BACKEND_PORT:-8100}"
    depends_on:
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      REDIS_URL: "redis://redis:6379"
    networks:
      - opengpts
    command: ["poetry", "run", "uvicorn", "app.server:app", "--host", "0.0.0.0", "--port", "${BACKEND_PORT:-8100}"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - opengpts
    command: ["yarn", "dev"]


volumes:
  redis-data:

networks:
  opengpts:
    driver: bridge
