version: "3"

services:
  sqlite-setup:
    build:
      context: tools/sqlite_migrate
    volumes:
      - ./backend:/backend
    command: ["migrate", "-path", "/backend/migrations", "-database", "sqlite3://opengpts.db", "up"]
  backend:
    container_name: opengpts-backend
    build:
      context: backend
    ports:
      - "8100:8000" # Backend is accessible on localhost:8100
    depends_on:
      sqlite-setup:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - ./backend:/backend
    environment:
      STORAGE_TYPE: "sqlite"
    command:
      - --reload
  frontend:
    container_name: opengpts-frontend
    build:
      context: frontend
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend/src:/frontend/src
    ports:
      - "5173:5173" # Frontend is accessible on localhost:5173
    environment:
      VITE_BACKEND_URL: "http://backend:8000"
